### ISSUE TITLE
捷径发布问题

### ISSUE THREAD

**Issue by In1t0** [Gkirito/autocheckinXC#1]
有的同学没有代理不能访问捷径链接，可否把该捷径发布在第三方社区？如sharecuts.cn

**Comment by Gkirito** [comment]
可以的

**Comment by Gkirito** [comment]
发布审核中

**Comment by Gkirito** [comment]
> 有的同学没有代理不能访问捷径链接，可否把该捷径发布在第三方社区？如sharecuts.cn

啊，好像发布不成功，估计不会让通过

**Comment by In1t0** [comment]
https://sharecuts.cn/shortcut/9491
注明了作者和项目地址

**Comment by Gkirito** [comment]
> https://sharecuts.cn/shortcut/9491
> 注明了作者和项目地址

👌，我首页也放一个
